"""Init

Revision ID: 22edea24c727
Revises: 9a0fa29f441e
Create Date: 2024-08-24 16:44:02.709652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22edea24c727'
down_revision: Union[str, None] = '9a0fa29f441e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('photo', sa.String(length=500), nullable=True))
    op.drop_column('photos', 'photos')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('photos', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('photos', 'photo')
    # ### end Alembic commands ###
