"""Init

Revision ID: 8a18bcd7233d
Revises: 426ea60aaa13
Create Date: 2024-08-24 20:40:01.516030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a18bcd7233d'
down_revision: Union[str, None] = '426ea60aaa13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'description')
    # ### end Alembic commands ###
