"""Init

Revision ID: d583d81e29d8
Revises: 15c1fe9dd37e
Create Date: 2024-09-01 18:08:07.866602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd583d81e29d8'
down_revision: Union[str, None] = '15c1fe9dd37e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('qrcode_user_id_fkey', 'qrcode', type_='foreignkey')
    op.create_foreign_key(None, 'qrcode', 'photo', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'qrcode', type_='foreignkey')
    op.create_foreign_key('qrcode_user_id_fkey', 'qrcode', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
